# Security Analysis using GitHub CodeQL
# More information here: https://github.com/github/codeql-action

name: Security analysis with GitHub CodeQL

on:
  push:
    branches:
      - dev
      - staging
      - master
  pull_request:
    branches:
      - dev
      - staging
      - master

jobs:
  security-analysis:
    name: Security analysis with GitHub CodeQL
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
