# Check code style and test package

# TODO: Fix problem: gets triggered on pull request to staging from dev
name: Lint and test code
on:
  push:
    branches-ignore:
      - master
      - staging
      - readthedocs

jobs:
  test:
    name: Test package code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install required packages
        run: |
          python3 -m pip install --user --upgrade -r requirements/testing.txt

      - name: Code style check
        run: python3 -m flake8 --verbose --config=setup.cfg --exit-zero . 2>&1

      - name: Test codebase
        run: python3 -m pytest -v -s
        env:
          LOYVERSE_ACCESS_TOKEN: ${{ secrets.loyverse_access_token }}
